paths:
  /api/products:
    get:
      summary: Obtener todos los productos
      tags:
        - Products
      responses:
        '200':
          description: Obtiene todos los productos de la base de datos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'
        '500':
          description: Error en el servidor
    post:
      summary: Crear producto
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/UpdateProduct'
      responses:
        '200':
          description: El producto se creo correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    $ref: "#components/schemas/Product"
        '500':
          description: Error en el servidor

  /api/products/{pid}:
     put:
      summary: Actualizar producto
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: pid es el id del producto que quiere actualizar
          schema:
            $type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/UpdateProduct'
      responses:
        '200':
          description: El producto se actualizo correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    $ref: "#components/schemas/Product"
        '500':
          description: Error en el servidor

components:
  schemas:
    Product:
      type: array
      items:
        type: object
        properties:
          _id:
            type: ObjectId
            description: id del producto
          title:
            type: string
            description: Titulo del producto
          description:
            type: string
            description: Descripcion del producto
          code:
            type: string
            description: Codigo del producto
          price:
            type: number
            description: Precio del producto
          status:
            type: boolean
            description: 
          stock:
            type: number
            description: Unidades disponibles del producto
          category:
            type: string
            description: Categoria del producto
          thumbnail:
            type: string
            description: url de imaneg del producto
      example:
        id: ObjectId('65850ef678ee3f212c45bb1e')
        title: 'smart tv'
        description: "smart tv 32 pls "
        code: 'abc123'
        price: 100
        status: true
        stock: 20
        category: "electro"
        thumbnail: ""
  requestBodies:
    UpdateProduct:
      type: object
      properties:
        title:
          type: string
          description: Titulo del producto
        description:
          type: string
          description: Descripcion del producto
        code:
          type: string
          description: Codigo del producto
        price:
          type: number
          description: Precio del producto
        status:
          type: boolean
          description: 
        stock:
          type: number
          description: Unidades disponibles del producto
        category:
          type: string
          description: Categoria del producto
        thumbnail:
          type: array
          description: url del producto
          items:
            type: string
            description: url de imagen del producto
      example:
        title: 'smart tv'
        description: "smart tv 42 pls "
        code: 'abc124'
        price: 100
        status: true
        stock: 20
        category: "electro"
        thumbnail: ""
